// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: consts/consts.proto

package consts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enable        *bool                  `protobuf:"varint,1,opt,name=enable" json:"enable,omitempty"`
	Suffix        *string                `protobuf:"bytes,2,opt,name=suffix" json:"suffix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileOptions) Reset() {
	*x = FileOptions{}
	mi := &file_consts_consts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOptions) ProtoMessage() {}

func (x *FileOptions) ProtoReflect() protoreflect.Message {
	mi := &file_consts_consts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOptions.ProtoReflect.Descriptor instead.
func (*FileOptions) Descriptor() ([]byte, []int) {
	return file_consts_consts_proto_rawDescGZIP(), []int{0}
}

func (x *FileOptions) GetEnable() bool {
	if x != nil && x.Enable != nil {
		return *x.Enable
	}
	return false
}

func (x *FileOptions) GetSuffix() string {
	if x != nil && x.Suffix != nil {
		return *x.Suffix
	}
	return ""
}

var file_consts_consts_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*FileOptions)(nil),
		Field:         1333,
		Name:          "consts.fileOptions",
		Tag:           "bytes,1333,opt,name=fileOptions",
		Filename:      "consts/consts.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional consts.FileOptions fileOptions = 1333;
	E_FileOptions = &file_consts_consts_proto_extTypes[0] // Extension number not registered yet.
)

var File_consts_consts_proto protoreflect.FileDescriptor

const file_consts_consts_proto_rawDesc = "" +
	"\n" +
	"\x13consts/consts.proto\x12\x06consts\x1a google/protobuf/descriptor.proto\"=\n" +
	"\vFileOptions\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\x12\x16\n" +
	"\x06suffix\x18\x02 \x01(\tR\x06suffix:T\n" +
	"\vfileOptions\x12\x1c.google.protobuf.FileOptions\x18\xb5\n" +
	" \x01(\v2\x13.consts.FileOptionsR\vfileOptionsB&Z$github.com/guader/protogen/pb/consts"

var (
	file_consts_consts_proto_rawDescOnce sync.Once
	file_consts_consts_proto_rawDescData []byte
)

func file_consts_consts_proto_rawDescGZIP() []byte {
	file_consts_consts_proto_rawDescOnce.Do(func() {
		file_consts_consts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_consts_consts_proto_rawDesc), len(file_consts_consts_proto_rawDesc)))
	})
	return file_consts_consts_proto_rawDescData
}

var file_consts_consts_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_consts_consts_proto_goTypes = []any{
	(*FileOptions)(nil),              // 0: consts.FileOptions
	(*descriptorpb.FileOptions)(nil), // 1: google.protobuf.FileOptions
}
var file_consts_consts_proto_depIdxs = []int32{
	1, // 0: consts.fileOptions:extendee -> google.protobuf.FileOptions
	0, // 1: consts.fileOptions:type_name -> consts.FileOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_consts_consts_proto_init() }
func file_consts_consts_proto_init() {
	if File_consts_consts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_consts_consts_proto_rawDesc), len(file_consts_consts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_consts_consts_proto_goTypes,
		DependencyIndexes: file_consts_consts_proto_depIdxs,
		MessageInfos:      file_consts_consts_proto_msgTypes,
		ExtensionInfos:    file_consts_consts_proto_extTypes,
	}.Build()
	File_consts_consts_proto = out.File
	file_consts_consts_proto_goTypes = nil
	file_consts_consts_proto_depIdxs = nil
}
