// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: enums/enums.proto

package enums

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enable        *bool                  `protobuf:"varint,1,opt,name=enable" json:"enable,omitempty"`
	Suffix        *string                `protobuf:"bytes,2,opt,name=suffix" json:"suffix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileOptions) Reset() {
	*x = FileOptions{}
	mi := &file_enums_enums_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOptions) ProtoMessage() {}

func (x *FileOptions) ProtoReflect() protoreflect.Message {
	mi := &file_enums_enums_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOptions.ProtoReflect.Descriptor instead.
func (*FileOptions) Descriptor() ([]byte, []int) {
	return file_enums_enums_proto_rawDescGZIP(), []int{0}
}

func (x *FileOptions) GetEnable() bool {
	if x != nil && x.Enable != nil {
		return *x.Enable
	}
	return false
}

func (x *FileOptions) GetSuffix() string {
	if x != nil && x.Suffix != nil {
		return *x.Suffix
	}
	return ""
}

type EnumOptions struct {
	state              protoimpl.MessageState          `protogen:"open.v1"`
	ValidationFunction *EnumOptions_ValidationFunction `protobuf:"bytes,1,opt,name=validationFunction" json:"validationFunction,omitempty"`
	ErrMethod          *EnumOptions_ErrMethod          `protobuf:"bytes,2,opt,name=errMethod" json:"errMethod,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EnumOptions) Reset() {
	*x = EnumOptions{}
	mi := &file_enums_enums_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumOptions) ProtoMessage() {}

func (x *EnumOptions) ProtoReflect() protoreflect.Message {
	mi := &file_enums_enums_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumOptions.ProtoReflect.Descriptor instead.
func (*EnumOptions) Descriptor() ([]byte, []int) {
	return file_enums_enums_proto_rawDescGZIP(), []int{1}
}

func (x *EnumOptions) GetValidationFunction() *EnumOptions_ValidationFunction {
	if x != nil {
		return x.ValidationFunction
	}
	return nil
}

func (x *EnumOptions) GetErrMethod() *EnumOptions_ErrMethod {
	if x != nil {
		return x.ErrMethod
	}
	return nil
}

type EnumValueOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           *string                `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumValueOptions) Reset() {
	*x = EnumValueOptions{}
	mi := &file_enums_enums_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumValueOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumValueOptions) ProtoMessage() {}

func (x *EnumValueOptions) ProtoReflect() protoreflect.Message {
	mi := &file_enums_enums_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumValueOptions.ProtoReflect.Descriptor instead.
func (*EnumValueOptions) Descriptor() ([]byte, []int) {
	return file_enums_enums_proto_rawDescGZIP(), []int{2}
}

func (x *EnumValueOptions) GetMsg() string {
	if x != nil && x.Msg != nil {
		return *x.Msg
	}
	return ""
}

type EnumOptions_ValidationFunction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enable        *bool                  `protobuf:"varint,1,opt,name=enable" json:"enable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumOptions_ValidationFunction) Reset() {
	*x = EnumOptions_ValidationFunction{}
	mi := &file_enums_enums_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumOptions_ValidationFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumOptions_ValidationFunction) ProtoMessage() {}

func (x *EnumOptions_ValidationFunction) ProtoReflect() protoreflect.Message {
	mi := &file_enums_enums_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumOptions_ValidationFunction.ProtoReflect.Descriptor instead.
func (*EnumOptions_ValidationFunction) Descriptor() ([]byte, []int) {
	return file_enums_enums_proto_rawDescGZIP(), []int{1, 0}
}

func (x *EnumOptions_ValidationFunction) GetEnable() bool {
	if x != nil && x.Enable != nil {
		return *x.Enable
	}
	return false
}

type EnumOptions_ErrMethod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enable        *bool                  `protobuf:"varint,1,opt,name=enable" json:"enable,omitempty"`
	WithGrpc      *bool                  `protobuf:"varint,2,opt,name=withGrpc" json:"withGrpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumOptions_ErrMethod) Reset() {
	*x = EnumOptions_ErrMethod{}
	mi := &file_enums_enums_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumOptions_ErrMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumOptions_ErrMethod) ProtoMessage() {}

func (x *EnumOptions_ErrMethod) ProtoReflect() protoreflect.Message {
	mi := &file_enums_enums_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumOptions_ErrMethod.ProtoReflect.Descriptor instead.
func (*EnumOptions_ErrMethod) Descriptor() ([]byte, []int) {
	return file_enums_enums_proto_rawDescGZIP(), []int{1, 1}
}

func (x *EnumOptions_ErrMethod) GetEnable() bool {
	if x != nil && x.Enable != nil {
		return *x.Enable
	}
	return false
}

func (x *EnumOptions_ErrMethod) GetWithGrpc() bool {
	if x != nil && x.WithGrpc != nil {
		return *x.WithGrpc
	}
	return false
}

var file_enums_enums_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*FileOptions)(nil),
		Field:         1335,
		Name:          "enums.fileOptions",
		Tag:           "bytes,1335,opt,name=fileOptions",
		Filename:      "enums/enums.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*EnumOptions)(nil),
		Field:         1335,
		Name:          "enums.enumOptions",
		Tag:           "bytes,1335,opt,name=enumOptions",
		Filename:      "enums/enums.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*EnumValueOptions)(nil),
		Field:         1335,
		Name:          "enums.enum",
		Tag:           "bytes,1335,opt,name=enum",
		Filename:      "enums/enums.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional enums.FileOptions fileOptions = 1335;
	E_FileOptions = &file_enums_enums_proto_extTypes[0] // Extension number not registered yet.
)

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional enums.EnumOptions enumOptions = 1335;
	E_EnumOptions = &file_enums_enums_proto_extTypes[1] // Extension number not registered yet.
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional enums.EnumValueOptions enum = 1335;
	E_Enum = &file_enums_enums_proto_extTypes[2] // Extension number not registered yet.
)

var File_enums_enums_proto protoreflect.FileDescriptor

const file_enums_enums_proto_rawDesc = "" +
	"\n" +
	"\x11enums/enums.proto\x12\x05enums\x1a google/protobuf/descriptor.proto\"=\n" +
	"\vFileOptions\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\x12\x16\n" +
	"\x06suffix\x18\x02 \x01(\tR\x06suffix\"\x8f\x02\n" +
	"\vEnumOptions\x12U\n" +
	"\x12validationFunction\x18\x01 \x01(\v2%.enums.EnumOptions.ValidationFunctionR\x12validationFunction\x12:\n" +
	"\terrMethod\x18\x02 \x01(\v2\x1c.enums.EnumOptions.ErrMethodR\terrMethod\x1a,\n" +
	"\x12ValidationFunction\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\x1a?\n" +
	"\tErrMethod\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\x12\x1a\n" +
	"\bwithGrpc\x18\x02 \x01(\bR\bwithGrpc\"$\n" +
	"\x10EnumValueOptions\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg:S\n" +
	"\vfileOptions\x12\x1c.google.protobuf.FileOptions\x18\xb7\n" +
	" \x01(\v2\x12.enums.FileOptionsR\vfileOptions:S\n" +
	"\venumOptions\x12\x1c.google.protobuf.EnumOptions\x18\xb7\n" +
	" \x01(\v2\x12.enums.EnumOptionsR\venumOptions:O\n" +
	"\x04enum\x12!.google.protobuf.EnumValueOptions\x18\xb7\n" +
	" \x01(\v2\x17.enums.EnumValueOptionsR\x04enumB%Z#github.com/guader/protogen/pb/enums"

var (
	file_enums_enums_proto_rawDescOnce sync.Once
	file_enums_enums_proto_rawDescData []byte
)

func file_enums_enums_proto_rawDescGZIP() []byte {
	file_enums_enums_proto_rawDescOnce.Do(func() {
		file_enums_enums_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enums_enums_proto_rawDesc), len(file_enums_enums_proto_rawDesc)))
	})
	return file_enums_enums_proto_rawDescData
}

var file_enums_enums_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_enums_enums_proto_goTypes = []any{
	(*FileOptions)(nil),                    // 0: enums.FileOptions
	(*EnumOptions)(nil),                    // 1: enums.EnumOptions
	(*EnumValueOptions)(nil),               // 2: enums.EnumValueOptions
	(*EnumOptions_ValidationFunction)(nil), // 3: enums.EnumOptions.ValidationFunction
	(*EnumOptions_ErrMethod)(nil),          // 4: enums.EnumOptions.ErrMethod
	(*descriptorpb.FileOptions)(nil),       // 5: google.protobuf.FileOptions
	(*descriptorpb.EnumOptions)(nil),       // 6: google.protobuf.EnumOptions
	(*descriptorpb.EnumValueOptions)(nil),  // 7: google.protobuf.EnumValueOptions
}
var file_enums_enums_proto_depIdxs = []int32{
	3, // 0: enums.EnumOptions.validationFunction:type_name -> enums.EnumOptions.ValidationFunction
	4, // 1: enums.EnumOptions.errMethod:type_name -> enums.EnumOptions.ErrMethod
	5, // 2: enums.fileOptions:extendee -> google.protobuf.FileOptions
	6, // 3: enums.enumOptions:extendee -> google.protobuf.EnumOptions
	7, // 4: enums.enum:extendee -> google.protobuf.EnumValueOptions
	0, // 5: enums.fileOptions:type_name -> enums.FileOptions
	1, // 6: enums.enumOptions:type_name -> enums.EnumOptions
	2, // 7: enums.enum:type_name -> enums.EnumValueOptions
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	5, // [5:8] is the sub-list for extension type_name
	2, // [2:5] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_enums_enums_proto_init() }
func file_enums_enums_proto_init() {
	if File_enums_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enums_enums_proto_rawDesc), len(file_enums_enums_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_enums_enums_proto_goTypes,
		DependencyIndexes: file_enums_enums_proto_depIdxs,
		MessageInfos:      file_enums_enums_proto_msgTypes,
		ExtensionInfos:    file_enums_enums_proto_extTypes,
	}.Build()
	File_enums_enums_proto = out.File
	file_enums_enums_proto_goTypes = nil
	file_enums_enums_proto_depIdxs = nil
}
